 PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
   PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
    PREFIX owl:   <http://www.w3.org/2000/07/owl#>
	 PREFIX  p:    <http://www.co-ode.org/ontologies/pizza/pizza.owl#>
	  SELECT DISTINCT  *
	   WHERE
	     { ?targetPizza    rdfs:subClassOf   _:pizza .
				     _:pizza  rdf:type              owl:Restriction ;
					             owl:onProperty        p:hasTopping ;
									           owl:someValuesFrom    _:targetTopping .
														       _:targetTopping  owl:intersectionOf (p:PizzaTopping _:hotTopping) .
															       _:hotTopping  rdf:type              owl:Restriction ;
												             owl:onProperty        p:hasSpiciness ;
																           owl:someValueFrom p:Hot .

																					    }
